chore(readme): update readme with preferred install procedure
weahead/husky-config pull request #6
Opened 2020-01-07 15:18 UTC by lofgrenfredrik

2020-01-07 18:29 UTC, michaellopez requested changes

2020-01-07 18:29 UTC, michaellopez commented on README.md
> +This config and it's dependencies are included in We aheads tooling packages and don't need to be installed in new We ahead projects. Instead use one of the tooling packages that have all configs and
@lofgrenfredrik `needed for it's use` => `needed for its use`

2020-01-07 18:29 UTC, michaellopez commented on README.md
> +This config and it's dependencies are included in We aheads tooling packages and don't need to be installed in new We ahead projects. Instead use one of the tooling packages that have all configs and
@lofgrenfredrik `and it's dependencies` => `and its dependencies`

2020-01-07 18:29 UTC, michaellopez commented on README.md
> +This config and it's dependencies are included in We aheads tooling packages and don't need to be installed in new We ahead projects. Instead use one of the tooling packages that have all configs and
@lofgrenfredrik `We aheads` => ``We ahead`s``

2020-01-07 18:29 UTC, michaellopez commented on README.md
> +### Install the config by it's own
@lofgrenfredrik `it's` => `its`

2020-01-07 19:29 UTC, lofgrenfredrik commented
@michaellopez
fixed copy. 👍

2020-01-14 09:28 UTC, michaellopez approved these changes

2020-01-14 09:28 UTC, merged